// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_5_Web_Api_Portfolio_Project.Data;

namespace dotnet_5_Web_Api_Portfolio_Project.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220223154016_ItemInCartUpdate")]
    partial class ItemInCartUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsMainCart")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemInCartId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemInCartId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AmountInWarehouse")
                        .HasColumnType("int");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Ratting")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountInWarehouse = 100,
                            Description = "A car",
                            Name = "Car",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 2,
                            AmountInWarehouse = 56,
                            Description = "A carrot",
                            Name = "Carrot",
                            Ratting = (byte)3
                        },
                        new
                        {
                            Id = 3,
                            AmountInWarehouse = 47,
                            Description = "A plant",
                            Name = "Plant",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 4,
                            AmountInWarehouse = 5,
                            Description = "Boots",
                            Name = "Boots",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 5,
                            AmountInWarehouse = 13,
                            Description = "A shovel",
                            Name = "Shovel",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 6,
                            AmountInWarehouse = 17,
                            Description = "A chainsaw",
                            Name = "Chainsaw",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 7,
                            AmountInWarehouse = 26,
                            Description = "A black bag",
                            Name = "Black bag",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 8,
                            AmountInWarehouse = 59,
                            Description = "A bleach",
                            Name = "Bleach",
                            Ratting = (byte)6
                        },
                        new
                        {
                            Id = 9,
                            AmountInWarehouse = 1234,
                            Description = "A poster",
                            Name = "Poster",
                            Ratting = (byte)6
                        });
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.ItemInCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Ratting")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItemsInCart");
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGolden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubcribed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.Cart", b =>
                {
                    b.HasOne("dotnet_5_Web_Api_Portfolio_Project.Models.ItemInCart", null)
                        .WithMany("Carts")
                        .HasForeignKey("ItemInCartId");

                    b.HasOne("dotnet_5_Web_Api_Portfolio_Project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.Item", b =>
                {
                    b.HasOne("dotnet_5_Web_Api_Portfolio_Project.Models.Cart", null)
                        .WithMany("ItemList")
                        .HasForeignKey("CartId");
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.Cart", b =>
                {
                    b.Navigation("ItemList");
                });

            modelBuilder.Entity("dotnet_5_Web_Api_Portfolio_Project.Models.ItemInCart", b =>
                {
                    b.Navigation("Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
